name: build
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        #run: echo "::set-output name=matrix::{\"include\":[{\"repo\":\"test-test-kvv-org\",\"environment_name\":\"test\"},{\"repo\":\"test-sonar-repo\",\"environment_name\":\"test1\"}]}"
        run: echo "json=$(cat ${GITHUB_WORKSPACE}/structure.json)"
      - run: echo "::set-output name=matrix::toJSON($env.json}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - run: echo "${{ toJSON(matrix) }}"
#      - run: echo ${{ matrix.*.name }}
#      - run: echo ${{ matrix.*.time }}
