on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: vk-org/composite-action
          token: ${{ secrets.SUPER_TOKEN }}
          path: composite
      - uses: actions/checkout@v2
      - uses: ../composite
        with:
          registry_username: ${{secrets.REGISTRY_USERNAME}}
          registry_password: ${{secrets.REGISTRY_PASSWORD}}
          image_name: test-repo
